openapi: 3.0.1
info:
  title: WAF/CDN State API
  version: '1.0'
  contact:
    name: WAF/CDN
    x-slack-channel: '#wss-backend'
    x-source-code: 'https://github.com/gdcorp-partners/waf-cdn-state-api'
security:
  - sso-jwt: []
servers:
  - url: 'https://state.api.waf-cdn.{env}.aws.gdcld.net/'
    variables:
      env:
        default: 'dev-private'
        enum:
          - dev-private
          - dev
          - test
          - ote
          - prod

paths:
  '/state/v1/customers/{customerId}/sites/{siteId}/state':
    get:
      summary: returns the site state
      operationId: getSiteState
      parameters:
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/customerId'
        - $ref: '#/components/parameters/X-Request-Id'
      responses:
        '200':
          description: site state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteState'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
      tags:
        - /v1
    post:
      summary: Create a product site state
      operationId: CreateProductSiteState
      parameters:
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/customerId'
        - $ref: '#/components/parameters/X-Request-Id'
      requestBody:
        description: Create a product site state
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductStateUpdate'
      responses:
        '204':
          description: State created
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
      tags:
        - /v1
    patch:
      summary: Update a product site state
      operationId: updateProductSiteState
      parameters:
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/customerId'
        - $ref: '#/components/parameters/X-Request-Id'
      requestBody:
        description: Update a product site state
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductStateUpdate'
      responses:
        '204':
          description: State Updated
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
      tags:
        - /v1

components:
  parameters:
    siteId:
      name: siteId
      in: path
      description: ID of site
      required: true
      schema:
        type: string
    customerId:
      name: customerId
      description: An identifier for a customer
      in: path
      required: true
      schema:
        type: string
        format: uuid
    X-Request-Id:
      name: X-Request-Id
      required: false
      in: header
      description: A unique identifier for the request
      schema:
        type: string

  schemas:
    Error:
      x-error-model: true
      type: object
      properties:
        code:
          type: string
          format: error-code
          pattern: '^[A-Z_][A-Z0-9_]*$'
          description: 'Short identifier for the error, suitable for indicating the specific error within client code'
        message:
          type: string
          description: 'Human-readable, English description of the error'
        fields:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
                format: json-path
                pattern: '^[a-z_]([a-zA-Z0-9_.]*)*$'
                description: 1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error
              pathRelated:
                type: string
                format: json-path
                pattern: '^[a-z_]([a-zA-Z0-9_.]*)*$'
                description: JSONPath referring to the field on the object referenced by `path` containing an error
              code:
                type: string
                format: error-code
                pattern: '^[A-Z_][A-Z0-9_]*$'
                description: 'Short identifier for the error, suitable for indicating the specific error within client code'
              message:
                type: string
                description: 'Human-readable, English description of the error'
            required:
              - path
              - code
          minItems: 1
          description: 'List of the specific fields, and the errors found with their contents'
        stack:
          type: array
          items:
            type: string
          minItems: 1
          description: 'Stack trace indicating where the error occurred.<br/>NOTE: This attribute <strong>MAY</strong> be included for Development and Test environments. However, it <strong>MUST NOT</strong> be exposed from OTE nor Production systems'
      required:
        - code
    ErrorLimit:
      x-error-model: true
      additionalProperties: false
      allOf:
        - type: object
          properties:
            retryAfterSec:
              type: integer
              pattern: '^[0-9]+$'
              description: Number of seconds to wait before attempting a similar request
          required:
            - retryAfterSec
        - $ref: '#/components/schemas/Error'

    SiteState:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductState'
        revision:
          type: integer
          format: int32
        state:
          description: Site global state
          type: string
          enum:
            - PENDING
            - SUCCESS
            - FAILED
      required:
        - state
        - products
        - revision
    ProductStateUpdate:
      type: object
      properties:
        productState:
          $ref: '#/components/schemas/ProductState'
        revision:
          type: integer
          format: int32
      required:
        - productState
        - revision
    ProductState:
      type: object
      properties:
        type:
          type: string
          enum:
            - CLOUDFRONT
            - ACM
        state:
          type: string
          enum:
            - PENDING
            - SUCCESS
            - FAILED
        traceId:
          type: string
        error:
          description: 'Error description, in case it exists'
          type: string
        arn:
          description: AWS ARN
          type: string
      required:
        - type
        - state
  responses:
    '400':
      description: Query string and/or request body are malformed
      x-error-codes:
        - MALFORMED_INPUT
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: Authentication info not sent or is invalid
      x-error-codes:
        - UNAUTHORIZED
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Authenticated user is not allowed access
      x-error-codes:
        - ACCESS_DENIED
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Resource not found
      x-error-codes:
        - NOT_FOUND
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '409':
      description: Application-specific server state error
      x-error-codes:
        - CONFLICTING_STATUS
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '429':
      description: Too many requests received within interval
      x-error-codes:
        - RATE_LIMITED
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ErrorLimit'
    '500':
      description: Internal server error
      x-error-codes:
        - INTERNAL_SERVER_ERROR
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: Service is temporarily unavailable
      x-error-codes:
        - SERVICE_UNAVAILABLE
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    sso-jwt:
      type: apiKey
      description: 'Standard GoDaddy SSO header authorization: <code>sso-jwt (token)</code>'
      name: Authorization
      in: header
